<?php
?>
<div class="SocialLogon-checkout">
    <div class="<?php echo $this->_getColSet(); ?>">
        <?php if($this->_googleEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> SocialLogon-checkout-google">
            <h3><?php echo $this->__('Google Connect') ?></h3>
            <p><?php echo $this->__('You can continue with checkout using your <strong>Google</strong> account.') ?></p>
            <?php echo $this->getChildHtml('inchoo_socialconnect_checkout_google_button')?>
        </div>
        <?php endif; ?>
        <?php if($this->_facebookEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> SocialLogon-checkout-facebook">
            <h3><?php echo $this->__('Facebook Connect') ?></h3>
            <p><?php echo $this->__('You can continue with checkout using your <strong>Facebook</strong> account.') ?></p>
            <?php echo $this->getChildHtml('inchoo_socialconnect_checkout_facebook_button')?>
        </div>
        <?php endif; ?>
        <?php if($this->_twitterEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> SocialLogon-checkout-twitter">
            <h3><?php echo $this->__('Twitter Connect') ?></h3>
            <p><?php echo $this->__('You can continue with checkout using your <strong>Twitter</strong> account.') ?></p>
            <?php echo $this->getChildHtml('inchoo_socialconnect_checkout_twitter_button')?>
        </div>
        <?php endif; ?>
        <?php if($this->_linkedinEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> SocialLogon-checkout-linkedin">
            <h3><?php echo $this->__('LinkedIn Connect') ?></h3>
            <p><?php echo $this->__('You can continue with checkout using your <strong>Linkedin</strong> account.') ?></p>
            <?php echo $this->getChildHtml('inchoo_socialconnect_checkout_linkedin_button')?>
        </div>
        <?php endif; ?>        
    </div>
</div>
